spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bankapp;trustServerCertificate=true;
    username: sa
    password: Hieu2301*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.bankin.app: DEBUG

server:
  error:
    include-message: always

app:
  card:
    available-duration: 5 #year
    credit:
      interest-rate: 20 #percentage
      late-fee: 5 #percentage
      payment-due-date: 20 #20th of month
      limit: 3000 #USD

jwt:
  secret: hvsecret